### ISSUE TITLE
Objetos mapa destruidos

### ISSUE THREAD

**Issue by piratajr** [krachenko/PRUEBASPERSISTENCIA#6]
Los objetos del mapa (por ej torre de control aeropuerto altis), si los destruyes se guardan en la DB, y al volver a cargar la partida se carga el destruido más el propio del mapa. Se ven uno encima del otro.

**Comment by AlvaroRosado** [comment]
Arreglado!, pero queda debatir alguna cosa (rendimiento vs funcionalidad) ;)
