### ISSUE TITLE
Guardado inventario ace

### ISSUE THREAD

**Issue by AlvaroRosado** [krachenko/PRUEBASPERSISTENCIA#9]
En el guardado a la base de datos se guarda también la rueda o ruedas del inventario ace de los vehículos, con lo cual al cargar, aparece el vehículo y al lado una rueda de ace.
Hay que buscar la forma de o bien limitar que este guardado no se produzca, o de que se haga correctamente.

**Comment by piratajr** [comment]
Si no me equivoco, el vehiculo, al volver a cargar sale con una rueda de repuesto, con lo cual seria lo suyo que no la guardase.

**Comment by AlvaroRosado** [comment]
Arreglado!
